export const ACTUALIZAR_CARRITO = 'ACTUALIZAR_CARRITO';
export const MOSTRAR_MENSAJE = 'MOSTRAR_MENSAJE';
export const ELIMINA_PRODUCTO = 'ELIMINA_PRODUCTO';
export const ACTIVA_NOTIFICACION = 'ACTIVA_NOTIFICACION';
export const LIMPIAR_CARRITO = 'LIMPIAR_CARRITO';
export const OBTENER_STORAGE = 'OBTENER_STORAGE';
export const OBTENER_VALORTOTAL = 'OBTENER_VALORTOTAL';